# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4780d2bb863b6ac0ef4ebca7f78e2643f7af4067224b6fa8d5629647ca9a79e9853ecd11087e0f511022aead21a01bd6817fbf3668df8d848bcd862878b13692

test:
  secret_key_base: bf5379dd26c128c2d433fdb23709ef8aefbb2aa067d4ba07948fd9b0dcf5da80ca499814fc8142489529991f9eb37d29537f228053028769f509514ad58f8de4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
